In [14]:
import numpy as np
groceries_price1 = np.load('C:/Users/HP/Downloads/groceries/Gardens.npy')
groceries_price2 = np.load('C:/Users/HP/Downloads/groceries/Baghdad.npy')
groceries_price3 = np.load('C:/Users/HP/Downloads/groceries/Shini.npy')
groceries_price4 = np.load('C:/Users/HP/Downloads/groceries/Max mar.npy')
groceries_price5 = np.load('C:/Users/HP/Downloads/groceries/Karaz.npy')
groceries_price6 = np.load('C:/Users/HP/Downloads/groceries/Bravo.npy')
groceries_price7 = np.load('C:/Users/HP/Downloads/groceries/Abo Ahmad.npy')
groceries_price8 = np.load('C:/Users/HP/Downloads/groceries/Mawares.npy')
# Define your vegetable quantities
vegetables = np.array([2, 1.5, 3, 6, 1, 1, 2, 3])  # Lemon, Tomato, Potato, Watermelon, Zucchini, Eggplant, Apple, Panana

# Calculate total price at each grocery
total_price_grocery1 = np.dot(groceries_price1, vegetables)
total_price_grocery2 = np.dot(groceries_price2, vegetables)
total_price_grocery3 = np.dot(groceries_price3, vegetables)
total_price_grocery4 = np.dot(groceries_price4, vegetables)
total_price_grocery5 = np.dot(groceries_price5, vegetables)
total_price_grocery6 = np.dot(groceries_price6, vegetables)
total_price_grocery7 = np.dot(groceries_price7, vegetables)
total_price_grocery8 = np.dot(groceries_price8, vegetables)


# Find the grocery with the minimum total price
cheapest_grocery_index = np.argmin([total_price_grocery1, total_price_grocery2, total_price_grocery3,total_price_grocery4,total_price_grocery5,total_price_grocery6,total_price_grocery7,total_price_grocery8])

# Find the name of the cheapest grocery (assuming grocery names are stored in a list)
grocery_names = ["Gardens", "Baghdad", "Shini" ,"Max mar","Karaz", "Bravo","Abo Ahmad","Mawares"] # ... add other grocery names
cheapest_grocery_name = grocery_names[cheapest_grocery_index]

print("The cheapest grocery to buy these vegetables is:", cheapest_grocery_name)



The cheapest grocery to buy these vegetables is: Abo Ahmad
[ 4.   2.4  3.5  3.  10.   5.  12.   5. ]
[ 3.1  3.   3.5  3.   8.   5.  10.   5. ]
[2.7 2.  3.  2.  7.  2.  8.  3.5]
[ 3.5  3.   5.   3.  12.   5.  13.   4. ]
[3.  2.5 4.  1.5 8.  3.  7.  4. ]
[3.  3.  3.3 1.5 8.  3.  9.  3. ]
[2.  2.  3.3 1.5 8.  2.5 7.  3.3]
[ 2.3  2.   3.3  1.  12.   3.   7.   3.3]


<function numpy.extract(condition, arr)>